



help:
	@echo "------- quick command samples -------";
	@echo "";
	@echo "python road_image_collector.py  -r -i /dev/video0 -o ./test_captured_vdo.mp4 ";
	@echo "";
	@echo "";
	@echo "python road_image_collector.py  -r -i ./test_captured_vdo.mp4  -o  mylabels.csv -s ./dataset/123 ";
	@echo ""
	@echo "[NOTE] for label mode with the option -s, please ensure to create the folder for saved image"
	@echo "";
	@echo "";


